version: "3"
services:
  client:
    image: shigezo/angular:7.0.6
    build: .
    command: bash -c "npm install && ng build --prod"
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "4200:4200"
